### ISSUE TITLE
Bar chart shows error for duplicated data

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#120]
If the values are duplicated the bar chart shows this error 

![image](https://user-images.githubusercontent.com/2202483/77667381-7c36e900-6f58-11ea-96ea-ede5abd38bfa.png)

Like Excel, why we can not have this chart (without aggregation)?

![image](https://user-images.githubusercontent.com/2202483/77667724-f6676d80-6f58-11ea-841c-f2b2575bef52.png)

**Comment by reza1615** [comment]
maybe you can add **value** to the Aggregation drop-down list

**Comment by aschonfeld** [comment]
Great suggestion on the "No Aggregation" option!  That certainly is easy enough to add.  I originally guarded against having duplicate entries on the x-axis because I just assumed the chart would be unreadable in that case.

**Comment by aschonfeld** [comment]
fixed in v1.8.1

**Comment by reza1615** [comment]
Thanks. would you please make **No aggregation** as default?

**Comment by aschonfeld** [comment]
Good call, will do!

**Comment by reza1615** [comment]
It still doesn't work properly. for 

![image](https://user-images.githubusercontent.com/2202483/77841099-c4265d80-715c-11ea-9a30-c5fad8d3f3a4.png)

![image](https://user-images.githubusercontent.com/2202483/77841216-4b73d100-715d-11ea-8e57-d9d7924b5e37.png)

The chart should have separated bar for each value. based on 
https://stackoverflow.com/questions/53229671/python-bar-chart-with-duplicate-datetimes-in-index

`df.plot(kind='bar')`

**Comment by aschonfeld** [comment]
@reza1615 I've solved the issue, but until I can get a new version released if you select a value for "Barsort" it should fix it for you.
